Repository twelive/final-project, pull requests merged in 2023-11, with the labels that each got.

#2 Fix/bug: `craco` 라이브러리를 이용한 웹팩 설정 내 초기화 이슈 해결
  .gitmessage.txt
  craco.config.js
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  src/App.tsx
  tsconfig.json
  tsconfig.paths.json
Labels: 🐛 bug, :bookmark: setting

#3 Init, Style: GlobalStyles, PR 템플릿, assets 기본 설정
  .github/pull_request_template.md
  package-lock.json
  package.json
  public/index.html
  src/App.tsx
  src/GlobalStyles.ts
  src/assets/common-channel.svg
  src/assets/common-educate.svg
  src/assets/common-feedback.svg
  src/assets/common-game.svg
  src/assets/common-home.svg
  src/assets/common-keyboard.svg
  src/assets/common-live.svg
  src/assets/common-login.svg
  src/assets/common-me.svg
  src/assets/common-menu.svg
  src/assets/common-mic.svg
  src/assets/common-movie.svg
  src/assets/common-music.svg
  src/assets/common-podcast.svg
  src/assets/common-rank.svg
  src/assets/common-search.svg
  src/assets/common-service.svg
  src/assets/common-setting.svg
  src/assets/common-shopping.svg
  src/assets/common-shorts.svg
  src/assets/common-sports.svg
  src/assets/common-subscribe.svg
  src/assets/coomon-history.svg
  src/assets/detail-add.svg
  src/assets/detail-dislike.svg
  src/assets/detail-like.svg
  src/assets/detail-more.svg
  src/assets/detail-subscribed.svg
  src/assets/detail.share.svg
  src/assets/favicon.ico
Labels: ✍ documentation, :bookmark: setting

#7 Feat/navbar: `NavBar`, `NavButton` 컴포넌트 작성
  src/assets/common-home-click.svg
  src/assets/common-home.svg
  src/components/Common.tsx
  src/components/NavButton.tsx
  src/layouts/NavBar.tsx
Labels: ✨ feat, ➕ add, 👨‍💻 Typescript, 🎨 Styled-Component

#8 Style: `styled-components`의 ThemeProvider를 이용한 반응형 구현
  src/App.tsx
  src/theme.ts
Labels: 🎨 Styled-Component, :bookmark: setting

#18 Feat: 헤더 컴포넌트 반응형 구현
  package-lock.json
  package.json
  src/components/HeaderButton.tsx
  src/layouts/Header.tsx
Labels: ➕ add, 👨‍💻 Typescript, 🎨 Styled-Component

#19 Feat/navbar: Redux 상태 관리 라이브러리를 이용한 click event 작동
  src/App.tsx
  src/assets/common-me-click.svg
  src/assets/common-subscribe-click.svg
  src/components/NavButton.tsx
  src/layouts/NavBar.tsx
  src/reducers/navReducer.ts
  src/rootReducer.ts
  src/store/.Store.tsx
  src/store/store.ts
  src/types/index.d.ts
Labels: ✨ feat, ➕ add, 👨‍💻 Typescript, 🛠 Redux

#22 Feat: menubar 비저블 메뉴바 생성
  src/App.tsx
  src/assets/common-history.svg
  src/layouts/MenuBar.tsx
Labels: ✨ feat, ➕ add, 👨‍💻 Typescript, 🎆 react, 🎨 Styled-Component

#23 Feat : MainListPage 1차 완성
  src/App.tsx
  src/pages/.Common.tsx
  src/pages/MainListPage.tsx
  src/types/index.d.ts
Labels: ✨ feat, 👨‍💻 Typescript, 🎨 Styled-Component

#25 Fix/bug: 절대 경로 버그 해결
  craco.config.js
  tsconfig.json
  tsconfig.path.json
  tsconfig.paths.json
Labels: 🐛 bug, 👨‍💻 Typescript, :bookmark: setting

#24 Docs/template: 풀리퀘 템플릿 재작성
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ✍ documentation, :bookmark: setting

#26 Feat/router: Router 경로 설정
  src/App.tsx
  src/RootLayout.tsx
  src/Router.tsx
  src/pages/DetailPage.tsx
  src/pages/Error404Page.tsx
  src/pages/MainListPage.tsx
Labels: ✨ feat, 🚗 react router, ➕ add

#29 Feat: 비저블 메뉴바 Reducer를 이용하여 상태관리 및 클릭 시의 색상 변경
  src/App.tsx
  src/RootLayout.tsx
  src/components/HeaderButton.tsx
  src/layouts/Header.tsx
  src/layouts/MenuBar.tsx
  src/reducers/toggleReducer.ts
  src/rootReducer.ts
  src/types/index.d.ts
Labels: ✨ feat, 🚗 react router, ➕ add, 👨‍💻 Typescript, 🎆 react, 🎨 Styled-Component, 🛠 Redux

#32 Feat/detail: 해당 영상 페이지 마크업, 스타일링, 로직 작업
  src/App.tsx
  src/GlobalStyles.ts
  src/Router.tsx
  src/pages/DetailPage.tsx
  src/pages/MainListPage.tsx
  src/reducers/dataReducer.ts
  src/reducers/detailReducer.ts
  src/rootReducer.ts
  src/types/index.d.ts
  src/types/reducer.d.ts
Labels: ✨ feat, 🚗 react router, ➕ add, 👨‍💻 Typescript, 🎨 Styled-Component, 🛠 Redux, 🛒 json

#36 Feat : MainListPage 애니메이션 추가
  package-lock.json
  package.json
  src/pages/MainListPage.tsx
Labels: ✨ feat, 🎨 Framer-motion

#39 Feat/detail: 상세페이지 내 모바일 시안 및 데스크탑 관련 영상 스크롤 개선
  src/pages/DetailPage.tsx
Labels: ➕ add, 🎨 Styled-Component

#41 Feat: Header 다크모드 버튼 클릭시 전체 페이지 및 컴포넌트 다크모드 적용하였습니다.
  common-shorts-click.svg
  src/App.tsx
  src/GlobalStyles.ts
  src/assets/common-me-click.svg
  src/assets/common-shorts-click.svg
  src/assets/common-subscribe-click.svg
  src/assets/common-whitehome.svg
  src/assets/common-whitelogin.svg
  src/assets/common-whitemainlogo.svg
  src/assets/common-whiteme.svg
  src/assets/common-whitemenu.svg
  src/assets/common-whitemic.svg
  src/assets/common-whitesearch.svg
  src/assets/common-whiteshorts.svg
  src/assets/common-whitesubscribe.svg
  src/assets/detail-share.svg
  src/components/HeaderButton.tsx
  src/components/NavButton.tsx
  src/index.tsx
  src/layouts/Header.tsx
  src/layouts/NavBar.tsx
  src/pages/DetailPage.tsx
  src/pages/MainListPage.tsx
  src/reducers/themeReducer.ts
  src/rootReducer.ts
  src/theme.ts
  src/types/reducer.d.ts
Labels: ✨ feat, 🚗 react router, ➕ add, 👨‍💻 Typescript, 🎆 react, 🎨 Styled-Component, 🛠 Redux, :bookmark: setting

#44 Feat: togglemenubar 토글 백드롭기능 구현, Fix: nav바와 menubar Redux 타입 각각 정의
  src/assets/common-playlist.svg
  src/components/NavButton.tsx
  src/layouts/Header.tsx
  src/layouts/MenuBar.tsx
  src/layouts/NavBar.tsx
  src/reducers/navReducer.ts
  src/reducers/toggleReducer.ts
  src/types/reducer.d.ts
Labels: ✨ feat, ➕ add, 👨‍💻 Typescript, 🎆 react, 🎨 Styled-Component, 🛠 Redux

#48 Feat/detail: 데스크탑 관련영상목록 스크롤 스타일링
  src/pages/DetailPage.tsx
Labels: ✨ feat, ➕ add, 🎨 Framer-motion

#49 Feat/docs: Redux action.type, 절대 경로 정리
  common-shorts-click.svg
  src/App.test.tsx
  src/App.tsx
  src/GlobalStyles.ts
  src/RootLayout.tsx
  src/Router.tsx
  src/assets/common-shorts-click.svg
  src/components/HeaderButton.tsx
  src/components/NavButton.tsx
  src/index.tsx
  src/layouts/Footer.tsx
  src/layouts/Header.tsx
  src/layouts/MenuBar.tsx
  src/layouts/NavBar.tsx
  src/pages/DetailPage.tsx
  src/pages/MainListPage.tsx
  src/reducers/dataReducer.ts
  src/reducers/detailReducer.ts
  src/reducers/navReducer.ts
  src/reducers/themeReducer.ts
  src/reducers/toggleReducer.ts
  src/rootReducer.ts
  src/store/store.ts
  src/theme.ts
  src/types/reducer.d.ts
  tsconfig.path.json
Labels: ✍ documentation, :bookmark: setting

#52 Feat : DetailPage 무한 스크롤 구현
  src/pages/DetailPage.tsx
Labels: ✨ feat, 🎨 Styled-Component

#54 Feat/HomeButton: 홈 Link 작업
  src/components/HeaderButton.tsx
  src/hooks/.Common.tsx
  src/hooks/HomeLogo.tsx
  src/layouts/Header.tsx
  src/layouts/MenuBar.tsx
Labels: ➕ add, 🎨 Styled-Component

#55 Fix/Bug: 레이아웃 배치를 통해 리스트 글씨가 헤더의 위로 올라오는 버그 해결
  src/RootLayout.tsx
  src/layouts/Header.tsx
Labels: 🐛 bug, 🎨 Styled-Component

#57 Feat : YouTube API 를 이용한 렌더링
  .gitignore
  package-lock.json
  package.json
  public/index.html
  src/pages/DetailPage.tsx
  src/pages/MainListPage.tsx
  src/reducers/dataReducer.ts
Labels: ✨ feat, 🚩 Youtube API

#59 Feat : Spinner 추가
  package-lock.json
  package.json
  src/assets/common-spinner.svg
  src/components/Spinner.tsx
  src/pages/DetailPage.tsx
  src/pages/MainListPage.tsx
Labels: ✨ feat, 🎨 Styled-Component

#60 Feat: DetailPage에 댓글기능하는 CommentItem 컴포넌트 분리 후 CRUD 확인 완료하였습니다.
  .gitignore
  declarations.d.ts
  package-lock.json
  src/assets/detail-sort.svg
  src/assets/detail-whitesort.svg
  src/assets/장원영쟝.jpg
  src/client.ts
  src/components/CommentItem.tsx
  src/pages/DetailPage.tsx
  tsconfig.json
Labels: ✨ feat, 🚗 react router, ➕ add, 🎆 react, 🎨 Styled-Component, 🛠 Redux

#62 Feat : ErrorPage 구현
  src/Router.tsx
  src/pages/DetailPage.tsx
  src/pages/Error404Page.tsx
  src/pages/ErrorPage.tsx
  src/pages/MainListPage.tsx
Labels: ✨ feat, 🎨 Styled-Component

#64 Feat: 메뉴바에 들어가는 다크모드 아이콘 생성 추가/적용 완료하였습니다. + comment 부분 scroll 적용 완료
  package-lock.json
  package.json
  src/assets/common-whiteeducate.svg
  src/assets/common-whitefeedback.svg
  src/assets/common-whitegame.svg
  src/assets/common-whitehistory.svg
  src/assets/common-whitelive.svg
  src/assets/common-whitemovie.svg
  src/assets/common-whitemusic.svg
  src/assets/common-whiteplaylist.svg
  src/assets/common-whitepodcast.svg
  src/assets/common-whiterank.svg
  src/assets/common-whiteshopping.svg
  src/assets/common-whitesports.svg
  src/components/CommentItem.tsx
  src/layouts/MenuBar.tsx
  src/reducers/themeReducer.ts
Labels: ✨ feat, ➕ add, 👨‍💻 Typescript, 🎆 react, 🎨 Styled-Component, 🛠 Redux

#65 Feat: darkmode localstorage 저장하였습니다.
  src/layouts/Header.tsx
Labels: ✨ feat, 🚗 react router, ➕ add, 👨‍💻 Typescript, 🎆 react, 🎨 Styled-Component, 🛠 Redux

#66 Feat: darkmode localstorage 저장을 위한 themeReducer 수정했습니다.
  src/reducers/themeReducer.ts
Labels: ✨ feat, 🚗 react router, ➕ add, 🎆 react, 🎨 Styled-Component, 🛠 Redux

#67 Feat/search: 모바일 검색 기능 구현 (Header, SearchPage)
  src/Router.tsx
  src/assets/common-arrow-left.svg
  src/assets/common-whitearrow-left.svg
  src/components/HeaderButton.tsx
  src/hooks/DarkMode.tsx
  src/hooks/HeaderBackButton.tsx
  src/hooks/SearchButton.tsx
  src/layouts/Header.tsx
  src/pages/DetailPage.tsx
  src/pages/SearchPage.tsx
  src/reducers/searchReducer.ts
  src/rootReducer.ts
  src/types/reducer.d.ts
Labels: ✨ feat, 🚗 react router, ➕ add, 👨‍💻 Typescript, 🎆 react, 🎨 Styled-Component, 🛠 Redux, 🛒 json

#69 Feat/Search: 검색기록 리듀서 생성, 관련 헤더 스타일링
  src/components/HeaderButton.tsx
  src/hooks/DarkMode.tsx
  src/layouts/Header.tsx
  src/pages/SearchPage.tsx
  src/reducers/searchHistoryReducer.ts
  src/reducers/searchReducer.ts
  src/rootReducer.ts
  src/types/reducer.d.ts
Labels: ➕ add, 🎨 Styled-Component, 🛠 Redux, 🎨 Framer-motion, 🧰 Refactor

#71 Docs : README 작성, Rename : 프로필 이미지 이름 변경
  README.md
  src/assets/profile.jpg
Labels: ✍ documentation, ✨ feat, ➕ add

#72 Docs : README 수정
  README.md
Labels: ✍ documentation, ✨ feat, ➕ add
